apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployment
spec:
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-config-map
          livenessProbe:
            httpGet:
              port: 80
              path: /
            periodSeconds: 10
            failureThreshold: 3 #Qtd de vezes de falha no pod para ele reiniciar
            initialDelaySeconds: 20
          readinessProbe: #indica se esta pronta para receber requisições
            httpGet:
              port: 80
              path: /inserir_noticias.php
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 3
          resources:
            requests:
              cpu: 10m
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias
