apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP # Para acessar de dentro do cluster (ip fixo)
  selector:
    app: segundo-pod
  ports:
    - port: 9000
      targetPort: 80